Sqlink.Uni.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Sqlink.Uni.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Sqlink.Uni.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Sqlink.Uni.BL;
using System.Collections.Generic;
using System.Linq;

namespace Sqlink.Uni.Web.Pages
{
    //[IgnoreAntiforgeryToken(Order = 1001)]
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IUniRepository _uniRepository;
        
        public Enrollment Enrollment => _uniRepository.GetCurrentEenrollment();
        public IEnumerable<Course> Courses => _uniRepository.GetCourses(false);
        public IEnumerable<Course> EnrollmentCourses => _uniRepository.GetCourses(true);

        [TempData] 
        public string AlertMessaage { get; set; } 

        public IndexModel(ILogger<IndexModel> logger, IUniRepository uniRepository)
        {
            _logger = logger;
            _uniRepository = uniRepository;
        }

        public void OnGet()
        {
        }


        public void OnPost()
        {
        }
        
        public RedirectToPageResult OnPostRegistration()
        {
            _uniRepository.GetCreareEenrollment();
             return RedirectToPage("Index");
        }
        public RedirectToPageResult OnPostClearAllCourses()
        {
            _uniRepository.ClearCoursesFromEenrollment();
            return RedirectToPage("Index");
        }
        public RedirectToPageResult OnPostCancelEenrollment()
        {
            _uniRepository.CancelEenrollment();
            return RedirectToPage("Index");
        }
        public RedirectToPageResult OnPostCompletedEenrollment()
        {
            _uniRepository.CompletedEenrollment();
            return RedirectToPage("Index");
        }
        public RedirectToPageResult OnPostPayEenrollment()
        {
            _uniRepository.PayEenrollment(); // .ClearAllCourses(
            return RedirectToPage("Index");
        }
        public RedirectToPageResult OnPostAddCourseToEenrollment(int id)
        {
            _uniRepository.AddCourseToEenrollment(id ,out string message);

            AlertMessaage = message;

            return RedirectToPage("Index");
        }
        public string GetOperetionDisabled(EnrollmentOperetion enrollmentOperetion)
        {
            var enabled = false;
            if (Enrollment == null && enrollmentOperetion == EnrollmentOperetion.CreateRegistration)
            {
                enabled = true;
            }
            else if (Enrollment == null && enrollmentOperetion != EnrollmentOperetion.CreateRegistration)
            {
                enabled = false;
            }
            else if (!EnrollmentCourses.Any() && new[] { EnrollmentOperetion .ClearAllCourses,
                                                         EnrollmentOperetion.Complete
                                                       }.Contains(enrollmentOperetion))
            {
                enabled = false;
            }
            else
            {
                enabled = enrollmentOperetion.IsValidEnrollmentOperetion(Enrollment.State);
            }

            return enabled ? null : "disabled";
        }
    }
}

Sqlink.Uni.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sqlink.Uni.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Sqlink.Uni.Web/Pages/Index.cshtml
@page
@using Sqlink.Uni.BL
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


 <div class="row">


     <div >
        <form asp-page-handler="Registration" method="post">
            <button   disabled="@(Model.GetOperetionDisabled(EnrollmentOperetion.CreateRegistration))" class="btn btn-default">Registration </button>
        </form>
    </div>
      
    <div  >
        <form asp-page-handler="completedEenrollment" method="post">
            <button   disabled="@(Model.GetOperetionDisabled(EnrollmentOperetion.Complete))" class="btn btn-default">Completed</button>
        </form>
    </div>
    <div  >
        <form asp-page-handler="clearAllCourses" method="post">
            <button   disabled="@(Model.GetOperetionDisabled(EnrollmentOperetion.ClearAllCourses))" class="btn btn-default">Clear all courses</button>
        </form>
    </div>
  
     <div  >
        <form asp-page-handler="cancelEenrollment" method="post">
            <button   disabled="@(Model.GetOperetionDisabled(EnrollmentOperetion.Cancel))" class="btn btn-default">Cancel</button>
        </form>
    </div>
     <div >
        <form asp-page-handler="payEenrollment" method="post">
            <button  disabled="@(Model.GetOperetionDisabled(EnrollmentOperetion.Pay))" class="btn btn-default">Pay</button>
        </form>
    </div>
     <div>
      <div style="padding-top:7px;"> |  Current State =   @(Model?.Enrollment?.State.ToString() ?? "not registered") | <span style="color:red;"> @(Model?.AlertMessaage)</span>  </div> 
     </div>
    
    </div>
     <div>
          <form  id="courseForm" asp-page-handler="addCourseToEenrollment" method="post">
                </form>
     </div>
      

  <div id="table" class="table"> 
      <span>Available Courses</span>

      <table class="table"">
        <thead>
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Year</th>
          <th>Semester</th>
          <th>Mandatory</th>  
          <th>Time</th>   

          <th> </th>
        </tr>
        </thead>
        <tbody>
        @foreach (var course in Model.Courses)
        {
          <tr  > 
            <td >@course.Id</td>
            <td >@course.Name</td>
            <td >@course.Year</td>
            <td >@course.Semester</td>
            <td >@course.IsMandatory</td>
            <td >@course.CourseRangeTime() </td>
            <td>
                        <button type="submit"
                         disabled="@(Model.GetOperetionDisabled(EnrollmentOperetion.AddCourse))"
                        name="id"
                        value="@course.Id"
                        form="courseForm"
                        asp-page-handler="addCourseToEenrollment"
                        class="btn btn-rounded btn-sm my-0">
                  Add
                </button>
            </td>
          </tr>
        }
        </tbody>
      </table>
</div>


<div>


    </div>


  <div id="table" class="table"> 
      <span>Selected Courses</span>

      <table class="table"">
        <thead>
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Year</th>
          <th>Semester</th>
          <th>Mandatory</th>
          <th>Time</th>
          <th> &nbsp;&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var course in Model.EnrollmentCourses)
        {
          <tr  > 
            <td >@course.Id</td>
            <td >@course.Name</td>
            <td >@course.Year</td>
            <td >@course.Semester</td>
            <td >@course.IsMandatory</td>
            <td >@course.CourseRangeTime() </td>
            <td>&nbsp;&nbsp; </td>
          </tr>
        }
        </tbody>
      </table>
</div>

Sqlink.Uni.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sqlink.Uni.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Course Managment</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @*<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>*@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 -  Course Managment 
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>