Sqlink.Uni.Mvc/Models/ErrorViewModel.cs
using System;

namespace Sqlink.Uni.Mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Sqlink.Uni.Mvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Sqlink.Uni.BL;
using Sqlink.Uni.Mvc.Models;
using System.Collections.Generic;
using System.Diagnostics;

namespace Sqlink.Uni.Mvc.Controllers
{



    public class IndexModel : PageModel
    {
        //private static int _personId = 0;
        //private static readonly List<Person> Data = new Faker<Person>()
        //    .RuleFor(m => m.Id, f => _personId++)
        //    .RuleFor(p => p.Name, f => f.Name.FullName())
        //    .RuleFor(m => m.Age, f => f.Random.Number(18, 65))
        //    .RuleFor(m => m.CompanyName, f => f.Company.CompanyName())
        //    .RuleFor(m => m.Country, f => f.Address.Country())
        //    .RuleFor(m => m.City, f => f.Address.City())
        //    .Generate(20);

        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }


        public IEnumerable<Course> Courses { get; set; }

        //public List<Person> People => Data;

        public RedirectToPageResult OnPostRemove(int id)
        {
           // People.RemoveAll(p => p.Id == id);
            return RedirectToPage("Index");
        }
    }


    public class EnrollmentModel :  PageModel
    {
        public IEnumerable<Course> Courses { get; set; }

        public void Remove(int courseId)
        {
        }
    }

    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var courses = Course.GetCourses();

            var model = new EnrollmentModel
            {
                Courses = courses
            };

            return View(model);
        }

        //public RedirectToPageResult OnPostRemove(int id)
        //{
        //    return default;
        //    //People.RemoveAll(p => p.Id == id);
        //    //return RedirectToPage("Index");
        //}

        //public void Remove(int courseId)
        //{
        //}
            
        //public void AddCourse(int courseId)
        //{
        //    //var courses = Course.GetCourses();

        //    //var model = new EnrollmentModel
        //    //{
        //    //    Courses = courses
        //    //};

        //    //return View(model);
        //}
        

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Sqlink.Uni.Mvc/Views/Home/Index.cshtml
@using Sqlink.Uni.BL
@{
    ViewData["Title"] = "Home Page";
}
<form id="remove" method="post"></form>


<table>
    <tr>
        <td>Name</td>
        <td>Lecturer</td>
        <td>Action</td>
    </tr>

@foreach (Course course in Model.Courses)
        {
            <tr class="border text-center">
                <td>@course.Name</td>
                <td>@course.Lecturer</td>


                       <td>
              <span class="table-remove">
                <button type="submit"
                        name="id"
                        value="@course.Id"
                        form="remove"
                        asp-page-handler="Remove"
                        class="btn btn-danger btn-rounded btn-sm my-0">
                  Remove
                </button>
              </span>
            </td>

                @*<td>
                    <form method="post"  asp-page-handler="AddCourse" asp-route-courseId=@course.Id>
                        <input type="submit" value="view details" class="btn btn-sm" />
                    </form>
                </td>*@
            </tr>
        }

         
</table>

Sqlink.Uni.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sqlink.Uni.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sqlink.Uni.Mvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Sqlink.Uni.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>